### ISSUE TITLE
How to contribute? 

### ISSUE THREAD

**Issue by MehmetKaranlik** [devmehmetates/SwiftyKit#1]
@devmehmetates  Mümkünse yardımcı olmak isterim bu pakette, bir roadmap vesaire varmıdır ?

**Comment by devmehmetates** [comment]
Selamlar, bir kaç gün içinde bununla alakalı bir şey eklerim pakete. Şimdiden teşekkürler.

**Comment by devmehmetates** [comment]
Bu konuyla alakalı bir <a href="https://github.com/devmehmetates/SwiftyKit/blob/main/CONTRIBUTING.md">Readme</a> hazırladım. Roadmap olarak da UITableView gibi sınıflar yerine UISlider gibi küçük UI objelerinin extensionları ile devam etmeyi planlıyorum. Paketin amacı daha çok küçük elementleri cover edebilmek.
